parser: babel-eslint

env:
  browser: true
  node: true
  es6: true

globals:
  logger: true

extends:
# - standard-react
# - plugin:eslint-plugin-import/warnings
# - plugin:eslint-plugin-import/errors

plugins:
- react
- flowtype

rules:
  no-console: 0 # [loosen] override upstream (?)
  keyword-spacing: 2
  no-redeclare: 1
  no-undef: 2
  # no-unused-vars: [2, {vars: all, args: none, ignoreRestSiblings: true}]
  react/jsx-indent: 0
  react/jsx-indent-props: 0
  react/jsx-no-bind: [2, {allowArrowFunctions: true}] # Should reconsider arrow functions
  flowtype/boolean-style: [2, "boolean"]
  flowtype/define-flow-type: 1
