export const APP_SWARM_BIN = 'swarmbin'
export const APP_PLAYGROUND = 'playground'
export const PASTE_SWARM_BIN = 'swarmbin:paste:'
export const PASTE_PLAYGROUND = 'playground:paste:'
export const PERSIST_DATA_SWARM_BIN = 'swarmbin:persistData'
export const PERSIST_DATA_PLAYGROUND = 'playground:persistData'
export const USER_OPTIONS_SWARM_BIN = 'swarmbin:userOptions'
export const USER_OPTIONS_PLAYGROUND = 'playground:userOptions'
